version: '2'
services:
  sidebar-app:
    image: sidebar
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,swagger
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_DATASOURCE_URL=jdbc:mysql://sidebar-mysql:3306/sidebar?useUnicode=true&characterEncoding=utf8&useSSL=false&createDatabaseIfNotExist=true
      - JHIPSTER_SLEEP=30 # gives time for other services to boot before the application
      - SPRING_DATA_JEST_URI=http://sidebar-elasticsearch:9200
      - SPRING_ELASTICSEARCH_REST_URIS=http://sidebar-elasticsearch:9200
    ports:
      - 8080:8080
  sidebar-mysql:
    extends:
      file: mysql.yml
      service: sidebar-mysql
  sidebar-elasticsearch:
    extends:
      file: elasticsearch.yml
      service: sidebar-elasticsearch
